### ISSUE TITLE
HypervisorPresent bug

### ISSUE THREAD

**Issue by VelocityRa** [sondernextdoor/WindowsHardwareInfo#6]
Not using this project, just run across this copy/paste bug and thought I'd give you a heads up:

https://github.com/sondernextdoor/WindowsHardwareInfo/blob/main/hwid.h#L637
```cpp
		QueryWMI(L"Win32_ComputerSystem", L"Model", IsHypervisorPresent);
```
should be:
```cpp
		QueryWMI(L"Win32_ComputerSystem", L"HypervisorPresent", IsHypervisorPresent);
```

**Comment by sondernextdoor** [comment]
Good catch! Fixed.

Thank you :)
